[package]
name = "rubyec"
version = "0.1.0"
authors = ["Cobrand <cobrandw@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.6"

# change back to crates.io once https://github.com/fitzgen/generational-arena/pull/26 is fixed
generational-arena = { git = "https://github.com/Cobrand/generational-arena.git", rev = "99422a4" }

hibitset = "0.6"